CRS-3421/upgrade action
hellofresh/action-changed-files pull request #26
Opened 2022-12-07 16:39 UTC by raghavtan

Fix types

2022-12-07 16:54 UTC, klemmster requested changes
Noticed two more

2022-12-07 16:54 UTC, klemmster commented on neo/neo.py
> +        default_patterns: list = None,
```suggestion
        default_patterns: list | None = None,
```

The current way warns with:
`Type "None" cannot be assigned to type "list[Unknown]",
because "None" is not of type list :)

2022-12-07 16:54 UTC, klemmster commented on neo/neo.py
>          default_patterns: object = None,
```suggestion
        default_patterns: list | None = None,
```

2022-12-08 08:38 UTC, rina-spinne approved these changes

2022-12-08 08:45 UTC, merged